class stn():
    stns = [
    {}, {}, {}, {}, {}, {}, {}, {}, {},

    {
    'KRName' : '대화',
    'ENName' : 'Daehwa',
    'Num' : '309',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'Yes',
    'nextStop' : None,
    'nextToward' : '대화',
    'nextDistance' : None,
    'preStop' : '주엽',
    'preToward' : '오금',
    'preDistance' : '1.4km',
    'Company' : '한국철도공사',
    'Line' : '일산선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '주엽',
    'ENName' : 'Juyeop',
    'Num' : '310',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '대화',
    'nextToward' : '대화',
    'nextDistance' : '1.4km',
    'preStop' : '정발산',
    'preToward' : '오금',
    'preDistance' : '1.6km',
    'Company' : '한국철도공사',
    'Line' : '일산선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '정발산(고양아람누리)',
    'ENName' : 'Jeongbalsan(Aram Nuri Arts Center)',
    'Num' : '311',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '주엽',
    'nextToward' : '대화',
    'nextDistance' : '1.6km',
    'preStop' : '마두',
    'preToward' : '오금',
    'preDistance' : '0.9km',
    'Company' : '한국철도공사',
    'Line' : '일산선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '마두',
    'ENName' : 'Madu',
    'Num' : '312',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '정발산',
    'nextToward' : '대화',
    'nextDistance' : '0.9km',
    'preStop' : '백석',
    'preToward' : '오금',
    'preDistance' : '1.4km',
    'Company' : '한국철도공사',
    'Line' : '일산선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '백석(건강보험일산병원)',
    'ENName' : 'Baekseok(National Health Insurance Service Ilsan Hospital)',
    'Num' : '313',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '마두',
    'nextToward' : '대화',
    'nextDistance' : '1.4km',
    'preStop' : '대곡',
    'preToward' : '오금',
    'preDistance' : '2.5km',
    'Company' : '한국철도공사',
    'Line' : '일산선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '대곡',
    'ENName' : 'Daegok',
    'Num' : '314',
    'Transfer' : '경의중앙선',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '백석',
    'nextToward' : '대화',
    'nextDistance' : '2.5km',
    'preStop' : '화정',
    'preToward' : '오금',
    'preDistance' : '2.1km',
    'Company' : '한국철도공사',
    'Line' : '일산선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '화정',
    'ENName' : 'Hwajeong',
    'Num' : '315',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '대곡',
    'nextToward' : '대화',
    'nextDistance' : '2.1km',
    'preStop' : '원당',
    'preToward' : '오금',
    'preDistance' : '2.6km',
    'Company' : '한국철도공사',
    'Line' : '일산선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '원당',
    'ENName' : 'Wondang',
    'Num' : '316',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '화정',
    'nextToward' : '대화',
    'nextDistance' : '2.6km',
    'preStop' : '원흥',
    'preToward' : '오금',
    'preDistance' : '2.9km',
    'Company' : '한국철도공사',
    'Line' : '일산선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '원흥',
    'ENName' : 'Wonheung',
    'Num' : '317',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '원당',
    'nextToward' : '대화',
    'nextDistance' : '2.9km',
    'preStop' : '삼송',
    'preToward' : '오금',
    'preDistance' : '2.1km',
    'Company' : '한국철도공사',
    'Line' : '일산선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '삼송',
    'ENName' : 'Samsong',
    'Num' : '318',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'Yes',
    'nextStop' : '원흥',
    'nextToward' : '대화',
    'nextDistance' : '2.1km',
    'preStop' : '지축',
    'preToward' : '오금',
    'preDistance' : '1.7km',
    'Company' : '한국철도공사',
    'Line' : '일산선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '지축',
    'ENName' : 'Jichuk',
    'Num' : '319',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '삼송',
    'nextToward' : '대화',
    'nextDistance' : '1.7km',
    'preStop' : '구파발',
    'preToward' : '오금',
    'preDistance' : '1.5km',
    'Company' : '한국철도공사 / 서울교통공사',
    'Line' : '일산선 / 서울 지하철 3호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '구파발',
    'ENName' : 'Gupabal',
    'Num' : '320',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'Yes',
    'nextStop' : '지축',
    'nextToward' : '대화',
    'nextDistance' : '1.5km',
    'preStop' : '연신내',
    'preToward' : '오금',
    'preDistance' : '2.0km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 3호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '연신내',
    'ENName' : 'Yeonsinnae',
    'Num' : '321',
    'Transfer' : '6호선 응암순환',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '구파발',
    'nextToward' : '대화',
    'nextDistance' : '2.0km',
    'preStop' : '불광',
    'preToward' : '오금',
    'preDistance' : '1.3km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 3호선',
    'watchStep' : 'Yes'
    },

    {
    'KRName' : '불광',
    'ENName' : 'Bulgwang',
    'Num' : '322',
    'Transfer' : '6호선 응암순환',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '연신내',
    'nextToward' : '대화',
    'nextDistance' : '1.3km',
    'preStop' : '녹번',
    'preToward' : '오금',
    'preDistance' : '1.1km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 3호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '녹번',
    'ENName' : 'Nokbeon',
    'Num' : '323',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '불광',
    'nextToward' : '대화',
    'nextDistance' : '1.1km',
    'preStop' : '홍제',
    'preToward' : '오금',
    'preDistance' : '1.6km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 3호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '홍제',
    'ENName' : 'Hongje',
    'Num' : '324',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '녹번',
    'nextToward' : '대화',
    'nextDistance' : '1.6km',
    'preStop' : '무악재',
    'preToward' : '오금',
    'preDistance' : '0.9km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 3호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '무악재',
    'ENName' : 'Muakjae',
    'Num' : '325',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '홍제',
    'nextToward' : '대화',
    'nextDistance' : '0.9km',
    'preStop' : '독립문',
    'preToward' : '오금',
    'preDistance' : '1.1km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 3호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '독립문',
    'ENName' : 'Dongnimmun',
    'Num' : '326',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'lastTrain',
    'nextStop' : '무악재',
    'nextToward' : '대화',
    'nextDistance' : '1.1km',
    'preStop' : '경복궁',
    'preToward' : '오금',
    'preDistance' : '1.6km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 3호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '경복궁(정부서울청사)',
    'ENName' : 'Gyeongbokgung(Government Complex-Seoul)',
    'Num' : '327',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '독립문',
    'nextToward' : '대화',
    'nextDistance' : '1.6km',
    'preStop' : '안국',
    'preToward' : '오금',
    'preDistance' : '1.1km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 3호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '안국(현대건설)',
    'ENName' : 'Anguk(Hyundai E & C)',
    'Num' : '328',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '경복궁',
    'nextToward' : '대화',
    'nextDistance' : '1.1km',
    'preStop' : '종로3가',
    'preToward' : '오금',
    'preDistance' : '1.0km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 3호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '종로3가(탑골공원)',
    'ENName' : 'Jongno 3(sam)-ga(Tapgol Park)',
    'Num' : '329',
    'Transfer' : '1호선,\n5호선',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '안국',
    'nextToward' : '대화',
    'nextDistance' : '1.0km',
    'preStop' : '을지로3가',
    'preToward' : '오금',
    'preDistance' : '0.6km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 3호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '을지로3가(BC카드)',
    'ENName' : 'Euljiro 3(sam)-ga(BC Card)',
    'Num' : '330',
    'Transfer' : '2호선',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '종로3가',
    'nextToward' : '대화',
    'nextDistance' : '0.6km',
    'preStop' : '충무로',
    'preToward' : '오금',
    'preDistance' : '0.7km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 3호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '충무로',
    'ENName' : 'Chungmuro',
    'Num' : '331',
    'Transfer' : '4호선',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '을지로3가',
    'nextToward' : '대화',
    'nextDistance' : '0.7km',
    'preStop' : '동대입구',
    'preToward' : '오금',
    'preDistance' : '0.9km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 3호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '동대입구',
    'ENName' : 'Dongguk Univ.',
    'Num' : '332',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '충무로',
    'nextToward' : '대화',
    'nextDistance' : '0.9km',
    'preStop' : '약수',
    'preToward' : '오금',
    'preDistance' : '0.7km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 3호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '약수',
    'ENName' : 'Yaksu',
    'Num' : '333',
    'Transfer' : '6호선',
    'Doors' : '왼쪽',
    'Terminal' : 'lastTrain',
    'nextStop' : '동대입구',
    'nextToward' : '대화',
    'nextDistance' : '0.7km',
    'preStop' : '금호',
    'preToward' : '오금',
    'preDistance' : '0.8km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 3호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '금호',
    'ENName' : 'Geumho',
    'Num' : '334',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '약수',
    'nextToward' : '대화',
    'nextDistance' : '0.8km',
    'preStop' : '옥수',
    'preToward' : '오금',
    'preDistance' : '0.8km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 3호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '옥수',
    'ENName' : 'Oksu',
    'Num' : '335',
    'Transfer' : '경의중앙선',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '금호',
    'nextToward' : '대화',
    'nextDistance' : '0.8km',
    'preStop' : '압구정',
    'preToward' : '오금',
    'preDistance' : '2.1km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 3호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '압구정(현대백화점)',
    'ENName' : 'Apgujeong(Hyundai Department Store)',
    'Num' : '336',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'lastTrain',
    'nextStop' : '옥수',
    'nextToward' : '대화',
    'nextDistance' : '2.1km',
    'preStop' : '신사',
    'preToward' : '오금',
    'preDistance' : '1.5km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 3호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '신사',
    'ENName' : 'Sinsa',
    'Num' : '337',
    'Transfer' : '신분당선',
    'Doors' : '오른쪽',
    'Terminal' : 'Yes',
    'nextStop' : '압구정',
    'nextToward' : '대화',
    'nextDistance' : '1.5km',
    'preStop' : '잠원',
    'preToward' : '오금',
    'preDistance' : '0.9km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 3호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '잠원',
    'ENName' : 'Jamwon',
    'Num' : '338',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '신사',
    'nextToward' : '대화',
    'nextDistance' : '0.9km',
    'preStop' : '고속터미널',
    'preToward' : '오금',
    'preDistance' : '1.2km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 3호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '고속터미널',
    'ENName' : 'Express Bus Terminal',
    'Num' : '339',
    'Transfer' : '7호선,\n9호선',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '잠원',
    'nextToward' : '대화',
    'nextDistance' : '1.2km',
    'preStop' : '교대',
    'preToward' : '오금',
    'preDistance' : '1.6km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 3호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '교대(법원, 검찰청)',
    'ENName' : "Seoul Nat'l Univ. of Education(Court & Procsecutor's Office)",
    'Num' : '340',
    'Transfer' : '2호선',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '고속터미널',
    'nextToward' : '대화',
    'nextDistance' : '1.6km',
    'preStop' : '남부터미널',
    'preToward' : '오금',
    'preDistance' : '0.9km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 3호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '남부터미널(예술의전당)',
    'ENName' : 'Nambu Bus Terminal(Seoul Arts Center)',
    'Num' : '341',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '교대',
    'nextToward' : '대화',
    'nextDistance' : '0.9km',
    'preStop' : '양재',
    'preToward' : '오금',
    'preDistance' : '1.8km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 3호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '양재(서초구청)',
    'ENName' : 'Yangjae(Seocho-gu Office)',
    'Num' : '342',
    'Transfer' : '신분당선',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '남부터미널',
    'nextToward' : '대화',
    'nextDistance' : '1.8km',
    'preStop' : '매봉',
    'preToward' : '오금',
    'preDistance' : '1.2km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 3호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '매봉',
    'ENName' : 'Maebong',
    'Num' : '343',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '양재',
    'nextToward' : '대화',
    'nextDistance' : '1.2km',
    'preStop' : '도곡',
    'preToward' : '오금',
    'preDistance' : '0.8km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 3호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '도곡',
    'ENName' : 'Dogok',
    'Num' : '344',
    'Transfer' : '수인분당선',
    'Doors' : '오른쪽',
    'Terminal' : 'lastTrain',
    'nextStop' : '매봉',
    'nextToward' : '대화',
    'nextDistance' : '0.8km',
    'preStop' : '대치',
    'preToward' : '오금',
    'preDistance' : '0.8km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 3호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '대치',
    'ENName' : 'Daechi',
    'Num' : '345',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '도곡',
    'nextToward' : '대화',
    'nextDistance' : '0.8km',
    'preStop' : '학여울',
    'preToward' : '오금',
    'preDistance' : '0.8km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 3호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '학여울',
    'ENName' : 'Hangnyeoul',
    'Num' : '346',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '대치',
    'nextToward' : '대화',
    'nextDistance' : '0.8km',
    'preStop' : '대청',
    'preToward' : '오금',
    'preDistance' : '0.9km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 3호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '대청(서울주택도시공사)',
    'ENName' : 'Daecheong(SH Corporation)',
    'Num' : '347',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '학여울',
    'nextToward' : '대화',
    'nextDistance' : '0.9km',
    'preStop' : '일원',
    'preToward' : '오금',
    'preDistance' : '1.2km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 3호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '일원',
    'ENName' : 'Irwon',
    'Num' : '348',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '대청',
    'nextToward' : '대화',
    'nextDistance' : '1.2km',
    'preStop' : '수서',
    'preToward' : '오금',
    'preDistance' : '1.8km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 3호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '수서',
    'ENName' : 'Suseo',
    'Num' : '349',
    'Transfer' : '수인분당선',
    'Doors' : '오른쪽(본선) / 왼쪽(입출고 차량)',
    'Terminal' : 'Yes',
    'nextStop' : '일원',
    'nextToward' : '대화',
    'nextDistance' : '1.8km',
    'preStop' : '가락시장',
    'preToward' : '오금',
    'preDistance' : '1.4km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 3호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '가락시장',
    'ENName' : 'Garak Market',
    'Num' : '350',
    'Transfer' : '8호선',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '수서',
    'nextToward' : '대화',
    'nextDistance' : '1.4km',
    'preStop' : '경찰병원',
    'preToward' : '오금',
    'preDistance' : '0.8km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 3호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '경찰병원',
    'ENName' : 'National Police Hospital',
    'Num' : '351',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '가락시장',
    'nextToward' : '대화',
    'nextDistance' : '0.8km',
    'preStop' : '오금',
    'preToward' : '오금',
    'preDistance' : '0.8km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 3호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '오금',
    'ENName' : 'Ogeum',
    'Num' : '352',
    'Transfer' : '5호선 마천지선',
    'Doors' : '오른쪽',
    'Terminal' : 'Yes',
    'nextStop' : '경찰병원',
    'nextToward' : '대화',
    'nextDistance' : '0.8km',
    'preStop': None,
    'preToward' : '오금',
    'preDistance': None,
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 3호선',
    'watchStep' : 'No'
    },
    ]
