class stn():
    stns = [
    {}, {}, {}, {}, {}, {}, {}, {}, {},

    {
    'KRName' : '대화',
    'ENName' : 'Daehwa',
    'Num' : '309',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'Yes',
    'nextStop' : None,
    'nextToward' : '대화',
    'nextDistance' : None,
    'preStop' : '주엽',
    'preToward' : '오금',
    'preDistance' : '1.4km',
    'Company' : '한국철도공사',
    'Line' : '일산선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '주엽',
    'ENName' : 'Juyeop',
    'Num' : '310',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '대화',
    'nextToward' : '대화',
    'nextDistance' : '1.4km',
    'preStop' : '정발산',
    'preToward' : '오금',
    'preDistance' : '1.6km',
    'Company' : '한국철도공사',
    'Line' : '일산선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '정발산(고양아람누리)',
    'ENName' : 'Jeongbalsan(Aram Nuri Arts Center)',
    'Num' : '311',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '주엽',
    'nextToward' : '대화',
    'nextDistance' : '1.6km',
    'preStop' : '마두',
    'preToward' : '오금',
    'preDistance' : '0.9km',
    'Company' : '한국철도공사',
    'Line' : '일산선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '마두',
    'ENName' : 'Madu',
    'Num' : '312',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '정발산',
    'nextToward' : '대화',
    'nextDistance' : '0.9km',
    'preStop' : '백석',
    'preToward' : '오금',
    'preDistance' : '1.4km',
    'Company' : '한국철도공사',
    'Line' : '일산선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '백석(건강보험일산병원)',
    'ENName' : 'Baekseok(National Health Insurance Service Ilsan Hospital)',
    'Num' : '313',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '마두',
    'nextToward' : '대화',
    'nextDistance' : '1.4km',
    'preStop' : '대곡',
    'preToward' : '오금',
    'preDistance' : '2.5km',
    'Company' : '한국철도공사',
    'Line' : '일산선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '대곡',
    'ENName' : 'Daegok',
    'Num' : '314',
    'Transfer' : '경의중앙선',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '백석',
    'nextToward' : '진접',
    'nextDistance' : '2.5km',
    'preStop' : '화정',
    'preToward' : '오금',
    'preDistance' : '2.1km',
    'Company' : '한국철도공사',
    'Line' : '일산선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '미아(서울사이버대학)',
    'ENName' : 'Mia(Seoul Cyber Univ.)',
    'Num' : '415',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '수유',
    'nextToward' : '진접',
    'nextDistance' : '1.4km',
    'preStop' : '미아사거리',
    'preToward' : '오이도',
    'preDistance' : '1.5km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 4호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '미아사거리',
    'ENName' : 'Miasageori',
    'Num' : '416',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '미아',
    'nextToward' : '진접',
    'nextDistance' : '1.5km',
    'preStop' : '길음',
    'preToward' : '오이도',
    'preDistance' : '1.3km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 4호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '길음',
    'ENName' : 'Gireum',
    'Num' : '417',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '미아사거리',
    'nextToward' : '진접',
    'nextDistance' : '1.3km',
    'preStop' : '성신여대입구',
    'preToward' : '오이도',
    'preDistance' : '1.4km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 4호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '성신여대입구(돈암)',
    'ENName' : "Sungshin Women's Univ.(Donam)",
    'Num' : '418',
    'Transfer' : '우이신설선',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '길음',
    'nextToward' : '진접',
    'nextDistance' : '1.4km',
    'preStop' : '한성대입구',
    'preToward' : '오이도',
    'preDistance' : '1.0km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 4호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '한성대입구(삼선교)',
    'ENName' : 'Hansung Univ.(Samseongyo)',
    'Num' : '419',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'lastTrain',
    'nextStop' : '성신여대입구',
    'nextToward' : '진접',
    'nextDistance' : '1.0km',
    'preStop' : '혜화',
    'preToward' : '오이도',
    'preDistance' : '0.9km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 4호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '혜화(서울대학교병원)',
    'ENName' : "Hyehwa(Seoul Nat'l Univ. Hospital)",
    'Num' : '420',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '한성대입구',
    'nextToward' : '진접',
    'nextDistance' : '0.9km',
    'preStop' : '동대문',
    'preToward' : '오이도',
    'preDistance' : '1.5km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 4호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '동대문',
    'ENName' : 'Dongdaemun',
    'Num' : '421',
    'Transfer' : '1호선',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '혜화',
    'nextToward' : '진접',
    'nextDistance' : '1.5km',
    'preStop' : '동대문역사문화공원',
    'preToward' : '오이도',
    'preDistance' : '0.7km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 4호선',
    'watchStep' : 'Yes'
    },

    {
    'KRName' : '동대문역사문화공원(DDP)',
    'ENName' : 'Dongdaemun History & Culture Park(DDP)',
    'Num' : '422',
    'Transfer' : '2호선,\n5호선',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '동대문',
    'nextToward' : '진접',
    'nextDistance' : '0.9km',
    'preStop' : '충무로',
    'preToward' : '오이도',
    'preDistance' : '1.3km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 4호선',
    'watchStep' : 'Yes'
    },

    {
    'KRName' : '충무로',
    'ENName' : 'Chungmuro',
    'Num' : '423',
    'Transfer' : '3호선',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '동대문역사문화공원',
    'nextToward' : '진접',
    'nextDistance' : '1.3km',
    'preStop' : '명동',
    'preToward' : '오이도',
    'preDistance' : '0.7km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 4호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '명동(우리금융타운)',
    'ENName' : 'Myeong-dong(Woori Finantial Town)',
    'Num' : '424',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '충무로',
    'nextToward' : '진접',
    'nextDistance' : '0.7km',
    'preStop' : '회현',
    'preToward' : '오이도',
    'preDistance' : '0.7km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 4호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '회현(남대문시장)',
    'ENName' : 'Hoehyeon(Namdaemun Market)',
    'Num' : '425',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '명동',
    'nextToward' : '진접',
    'nextDistance' : '0.7km',
    'preStop' : '서울역',
    'preToward' : '오이도',
    'preDistance' : '0.9km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 4호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '서울역',
    'ENName' : 'Seoul Station',
    'Num' : '426',
    'Transfer' : '1호선,\n공항철도,\n경의중앙선(시간표 확인 필요)',
    'Doors' : '왼쪽',
    'Terminal' : 'lastTrain',
    'nextStop' : '회현',
    'nextToward' : '진접',
    'nextDistance' : '0.9km',
    'preStop' : '숙대입구',
    'preToward' : '오이도',
    'preDistance' : '1.0km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 4호선',
    'watchStep' : 'Yes'
    },

    {
    'KRName' : '숙대입구(갈월)',
    'ENName' : "Sookmyung Women's Univ.(Garwol)",
    'Num' : '427',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '서울역',
    'nextToward' : '진접',
    'nextDistance' : '1.0km',
    'preStop' : '삼각지',
    'preToward' : '오이도',
    'preDistance' : '1.2km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 4호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '삼각지',
    'ENName' : 'Samgakji',
    'Num' : '428',
    'Transfer' : '6호선',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '숙대입구',
    'nextToward' : '진접',
    'nextDistance' : '1.2km',
    'preStop' : '신용산',
    'preToward' : '오이도',
    'preDistance' : '0.7km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 4호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '신용산(아모레퍼시픽)',
    'ENName' : 'Sinyongsan(AMOREPACIFIC)',
    'Num' : '429',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '삼각지',
    'nextToward' : '진접',
    'nextDistance' : '0.7km',
    'preStop' : '이촌',
    'preToward' : '오이도',
    'preDistance' : '1.3km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 4호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '이촌(국립중앙박물관)',
    'ENName' : 'Ichon(National Museum of Korea)',
    'Num' : '430',
    'Transfer' : '경의중앙선',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '신용산',
    'nextToward' : '진접',
    'nextDistance' : '1.3km',
    'preStop' : '동작',
    'preToward' : '오이도',
    'preDistance' : '2.7km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 4호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '동작(현충원)',
    'ENName' : 'Dongjak(Seoul National Cemetery)',
    'Num' : '431',
    'Transfer' : '9호선',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '이촌',
    'nextToward' : '진접',
    'nextDistance' : '2.7km',
    'preStop' : '총신대입구',
    'preToward' : '오이도',
    'preDistance' : '1.8km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 4호선',
    'watchStep' : 'Yes'
    },

    {
    'KRName' : '총신대입구(이수)',
    'ENName' : 'Chongshin Univ.(Isu)',
    'Num' : '432',
    'Transfer' : '7호선',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '동작',
    'nextToward' : '진접',
    'nextDistance' : '1.8km',
    'preStop' : '사당',
    'preToward' : '오이도',
    'preDistance' : '1.1km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 4호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '사당(대항병원)',
    'ENName' : 'Sadang(Daehang Hospital)',
    'Num' : '433',
    'Transfer' : '2호선',
    'Doors' : '왼쪽',
    'Terminal' : 'Yes',
    'nextStop' : '총신대입구',
    'nextToward' : '진접',
    'nextDistance' : '1.1km',
    'preStop' : '남태령',
    'preToward' : '오이도',
    'preDistance' : '1.6km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 4호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '남태령',
    'ENName' : 'Namtaeryeong',
    'Num' : '434',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'lastTrain',
    'nextStop' : '사당',
    'nextToward' : '진접',
    'nextDistance' : '1.6km',
    'preStop' : '선바위',
    'preToward' : '오이도',
    'preDistance' : '2.0km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 4호선 / 과천선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '선바위',
    'ENName' : 'Seonbawi',
    'Num' : '435',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '남태령',
    'nextToward' : '당고개',
    'nextDistance' : '2.0km',
    'preStop' : '경마공원',
    'preToward' : '오이도',
    'preDistance' : '1.0km',
    'Company' : '한국철도공사',
    'Line' : '과천선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '경마공원',
    'ENName' : 'Seoul Racecourse Park',
    'Num' : '436',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '선바위',
    'nextToward' : '당고개',
    'nextDistance' : '1.0km',
    'preStop' : '대공원',
    'preToward' : '오이도',
    'preDistance' : '0.9km',
    'Company' : '한국철도공사',
    'Line' : '과천선',
    'watchStep' : 'Yes'
    },

    {
    'KRName' : '대공원(서울랜드)',
    'ENName' : 'Seoul Grand Park(SeoulLand)',
    'Num' : '437',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'emergency',
    'nextStop' : '경마공원',
    'nextToward' : '당고개',
    'nextDistance' : '0.9km',
    'preStop' : '과천',
    'preToward' : '오이도',
    'preDistance' : '1.0km',
    'Company' : '한국철도공사',
    'Line' : '과천선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '과천',
    'ENName' : 'Gwacheon',
    'Num' : '438',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '대공원',
    'nextToward' : '당고개',
    'nextDistance' : '1.0km',
    'preStop' : '정부과천청사',
    'preToward' : '오이도',
    'preDistance' : '1.0km',
    'Company' : '한국철도공사',
    'Line' : '과천선',
    'watchStep' : 'Yes'
    },

    {
    'KRName' : '정부과천청사',
    'ENName' : 'Government Complex Gwacheon',
    'Num' : '439',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '과천',
    'nextToward' : '당고개',
    'nextDistance' : '1.0km',
    'preStop' : '인덕원',
    'preToward' : '오이도',
    'preDistance' : '3.0km',
    'Company' : '한국철도공사',
    'Line' : '과천선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '과천지식정보단지',
    'ENName' : 'Gwacheon Knowledge Information Complex',
    'Num' : '',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '정부과천청사',
    'nextToward' : '진접',
    'nextDistance' : '1.9km',
    'preStop' : '인덕원',
    'preToward' : '오이도',
    'preDistance' : '1.1km',
    'Company' : '한국철도공사',
    'Line' : '과천선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '인덕원',
    'ENName' : 'Indeogwon',
    'Num' : '440',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'emergency',
    'nextStop' : '정부과천청사',
    'nextToward' : '당고개',
    'nextDistance' : '3.0km',
    'preStop' : '평촌',
    'preToward' : '오이도',
    'preDistance' : '1.6km',
    'Company' : '한국철도공사',
    'Line' : '과천선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '평촌(한림대성심병원)',
    'ENName' : 'Pyeongchon(Hallym Univ. Sacred Heart Hospital)',
    'Num' : '441',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '인덕원',
    'nextToward' : '당고개',
    'nextDistance' : '1.6km',
    'preStop' : '범계',
    'preToward' : '오이도',
    'preDistance' : '1.3km',
    'Company' : '한국철도공사',
    'Line' : '과천선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '범계',
    'ENName' : 'Beomgye',
    'Num' : '442',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '평촌',
    'nextToward' : '당고개',
    'nextDistance' : '1.3km',
    'preStop' : '금정',
    'preToward' : '오이도',
    'preDistance' : '2.6km',
    'Company' : '한국철도공사',
    'Line' : '과천선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '금정',
    'ENName' : 'Geumjeong',
    'Num' : '443',
    'Transfer' : '1호선',
    'Doors' : '오른쪽',
    'Terminal' : 'lastTrain',
    'nextStop' : '범계',
    'nextToward' : '당고개',
    'nextDistance' : '2.6km',
    'preStop' : '산본',
    'preToward' : '오이도',
    'preDistance' : '2.3km',
    'Company' : '한국철도공사',
    'Line' : '과천선 / 안산선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '산본(원광대산본병원)',
    'ENName' : 'Sanbon(Wonkwang Univ. Sanbon Hospital)',
    'Num' : '444',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'lastTrain',
    'nextStop' : '금정',
    'nextToward' : '당고개',
    'nextDistance' : '2.3km',
    'preStop' : '수리산 / 상록수(급행)',
    'preToward' : '오이도',
    'preDistance' : '1.1km / 9.4km',
    'Company' : '한국철도공사',
    'Line' : '안산선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '수리산',
    'ENName' : 'Surisan',
    'Num' : '445',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '산본',
    'nextToward' : '당고개',
    'nextDistance' : '1.1km',
    'preStop' : '대야미',
    'preToward' : '오이도',
    'preDistance' : '2.6km',
    'Company' : '한국철도공사',
    'Line' : '안산선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '대야미',
    'ENName' : 'Daeyami',
    'Num' : '446',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '수리산',
    'nextToward' : '당고개',
    'nextDistance' : '2.6km',
    'preStop' : '반월',
    'preToward' : '오이도',
    'preDistance' : '2.0km',
    'Company' : '한국철도공사',
    'Line' : '안산선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '반월',
    'ENName' : 'Banwol',
    'Num' : '447',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '대야미',
    'nextToward' : '당고개',
    'nextDistance' : '2.0km',
    'preStop' : '상록수',
    'preToward' : '오이도',
    'preDistance' : '3.7km',
    'Company' : '한국철도공사',
    'Line' : '안산선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '상록수(안산대학교)',
    'ENName' : 'Sangnoksu(Ansan Univ.)',
    'Num' : '448',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '반월 / 산본(급행)',
    'nextToward' : '당고개',
    'nextDistance' : '3.7km / 9.4km',
    'preStop' : '한대앞 / 중앙(급행)',
    'preToward' : '오이도',
    'preDistance' : '1.5km / 3.1km',
    'Company' : '한국철도공사',
    'Line' : '안산선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '한대앞',
    'ENName' : 'Hanyang Univ. at Ansan',
    'Num' : '449',
    'Transfer' : '수인분당선',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '상록수',
    'nextToward' : '당고개',
    'nextDistance' : '1.5km',
    'preStop' : '중앙',
    'preToward' : '오이도',
    'preDistance' : '1.6km',
    'Company' : '한국철도공사',
    'Line' : '안산선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '중앙(서울예술대학교)',
    'ENName' : 'Jungang(Seoul Institute of Arts)',
    'Num' : '450',
    'Transfer' : '수인분당선',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '한대앞 / 상록수(급행)',
    'nextToward' : '당고개',
    'nextDistance' : '1.5km / 3.1km',
    'preStop' : '고잔 / 초지(급행)',
    'preToward' : '오이도',
    'preDistance' : '1.4km / 2.9km',
    'Company' : '한국철도공사',
    'Line' : '안산선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '고잔(고대안산병원)',
    'ENName' : 'Gojan(Korea Univ. Ansan Hospital)',
    'Num' : '451',
    'Transfer' : '수인분당선',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '중앙',
    'nextToward' : '당고개',
    'nextDistance' : '1.4km',
    'preStop' : '초지',
    'preToward' : '오이도',
    'preDistance' : '1.5km',
    'Company' : '한국철도공사',
    'Line' : '안산선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '초지(신안산대학교)',
    'ENName' : 'Choji(Shin Ansan Univ.)',
    'Num' : '452',
    'Transfer' : '수인분당선,\n서해선',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '고잔 / 중앙(급행)',
    'nextToward' : '당고개',
    'nextDistance' : '1.5km / 2.9km',
    'preStop' : '안산',
    'preToward' : '오이도',
    'preDistance' : '1.8km',
    'Company' : '한국철도공사',
    'Line' : '안산선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '안산',
    'ENName' : 'Ansan',
    'Num' : '453',
    'Transfer' : '수인분당선',
    'Doors' : '왼쪽',
    'Terminal' : 'Yes',
    'nextStop' : '초지',
    'nextToward' : '당고개',
    'nextDistance' : '1.8km',
    'preStop' : '신길온천 / 정왕(급행)',
    'preToward' : '오이도',
    'preDistance' : '2.2km / 5.1km',
    'Company' : '한국철도공사',
    'Line' : '안산선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '신길온천',
    'ENName' : 'Singil Oncheon',
    'Num' : '454',
    'Transfer' : '수인분당선',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '안산',
    'nextToward' : '당고개',
    'nextDistance' : '2.2km',
    'preStop' : '정왕',
    'preToward' : '오이도',
    'preDistance' : '2.9km',
    'Company' : '한국철도공사',
    'Line' : '안산선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '정왕(한국산업기술대)',
    'ENName' : 'Jeongwang(Tech Univ. of Korea)',
    'Num' : '455',
    'Transfer' : '수인분당선',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '신길온천 / 안산(급행)',
    'nextToward' : '당고개',
    'nextDistance' : '2.9km / 5.1km',
    'preStop' : '오이도',
    'preToward' : '오이도',
    'preDistance' : '1.4km',
    'Company' : '한국철도공사',
    'Line' : '안산선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '오이도',
    'ENName' : 'Oido',
    'Num' : '456',
    'Transfer' : '수인분당선',
    'Doors' : '왼쪽',
    'Terminal' : 'Yes',
    'nextStop' : '정왕',
    'nextToward' : '당고개',
    'nextDistance' : '1.4km',
    'preStop' : None,
    'preToward' : '오이도',
    'preDistance' : None,
    'Company' : '한국철도공사',
    'Line' : '안산선',
    'watchStep' : 'No'
    },
    ]
