class stn():
    stns = [{
    'KRName' : '소요산',
    'ENName' : 'Soyosan',
    'Num' : '100',
    'Transfer' : None,
    'Doors' : '오른쪽',
    'Terminal' : 'Yes',
    'nextStop' : None,
    'nextToward' : '소요산',
    'nextDistance' : None,
    'preStop' : '동두천',
    'preToward' : '인천',
    'preDistance' : '2.5km',
    'Company' : '한국철도공사',
    'Line' : '경원선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '동두천',
    'ENName' : 'Dongducheon',
    'Num' : '101',
    'Transfer' : None,
    'Doors' : '왼쪽',
    'Terminal' : 'Yes',
    'nextStop' : '소요산',
    'nextToward' : '소요산',
    'nextDistance' : '2.5km',
    'preStop' : '보산 / 동두천중앙(급행)',
    'preToward' : '인천',
    'preDistance' : '1.6km / 3.0km',
    'Company' : '한국철도공사',
    'Line' : '경원선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '보산',
    'ENName' : 'Bosan',
    'Num' : '102',
    'Transfer' : None,
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '동두천',
    'nextToward' : '소요산',
    'nextDistance' : '1.6km',
    'preStop' : '동두천중앙',
    'preToward' : '인천',
    'preDistance' : '1.4km',
    'Company' : '한국철도공사',
    'Line' : '경원선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '동두천중앙',
    'ENName' : 'Dongducheonjungang',
    'Num' : '103',
    'Transfer' : None,
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '보산 / 동두천(급행)',
    'nextToward' : '소요산',
    'nextDistance' : '1.4km / 3.0km',
    'preStop' : '지행',
    'preToward' : '인천',
    'preDistance' : '1.0km',
    'Company' : '한국철도공사',
    'Line' : '경원선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '지행',
    'ENName' : 'Jihaeng',
    'Num' : '104',
    'Transfer' : None,
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '동두천중앙',
    'nextToward' : '소요산',
    'nextDistance' : '1.0km',
    'preStop' : '덕정',
    'preToward' : '인천',
    'preDistance' : '5.6km',
    'Company' : '한국철도공사',
    'Line' : '경원선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '덕정(서정대학교)',
    'ENName' : 'Deokjeong(Seojeong Univ.)',
    'Num' : '105',
    'Transfer' : None,
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '지행',
    'nextToward' : '소요산',
    'nextDistance' : '5.6km',
    'preStop' : '덕계 / 양주(급행)',
    'preToward' : '인천',
    'preDistance' : '2.9km / 8.2km',
    'Company' : '한국철도공사',
    'Line' : '경원선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '덕계',
    'ENName' : 'Deokgye',
    'Num' : '106',
    'Transfer' : None,
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '덕정',
    'nextToward' : '소요산',
    'nextDistance' : '2.9km',
    'preStop' : '양주',
    'preToward' : '인천',
    'preDistance' : '5.3km',
    'Company' : '한국철도공사',
    'Line' : '경원선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '양주',
    'ENName' : 'Yangju',
    'Num' : '107',
    'Transfer' : None,
    'Doors' : '왼쪽',
    'Terminal' : 'Yes',
    'nextStop' : '덕계 / 덕정(급행)',
    'nextToward' : '소요산',
    'nextDistance' : '5.3km / 8.2km',
    'preStop' : '녹양 / 의정부(급행)',
    'preToward' : '인천',
    'preDistance' : '1.3km / 4.1km',
    'Company' : '한국철도공사',
    'Line' : '경원선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '녹양',
    'ENName' : 'Nokyang',
    'Num' : '108',
    'Transfer' : None,
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '양주',
    'nextToward' : '소요산',
    'nextDistance' : '1.3km',
    'preStop' : '가능',
    'preToward' : '인천',
    'preDistance' : '1.3km',
    'Company' : '한국철도공사',
    'Line' : '경원선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '가능(을지대병원)',
    'ENName' : 'Ganeung(Eulji Univ. Hospital)',
    'Num' : '109',
    'Transfer' : None,
    'Doors' : '왼쪽',
    'Terminal' : 'emergency',
    'nextStop' : '녹양',
    'nextToward' : '소요산',
    'nextDistance' : '1.3km',
    'preStop' : '의정부',
    'preToward' : '인천',
    'preDistance' : '1.2km',
    'Company' : '한국철도공사',
    'Line' : '경원선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '의정부',
    'ENName' : 'Uijeongbu',
    'Num' : '110',
    'Transfer' : None,
    'Doors' : '왼쪽',
    'Terminal' : 'Yes',
    'nextStop' : '가능 / 양주(급행)',
    'nextToward' : '소요산',
    'nextDistance' : '1.2km / 4.1km',
    'preStop' : '회룡',
    'preToward' : '인천',
    'preDistance' : '1.6km',
    'Company' : '한국철도공사',
    'Line' : '경원선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '회룡',
    'ENName' : 'Hoeryong',
    'Num' : '111',
    'Transfer' : '의정부 경전철',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '의정부',
    'nextToward' : '소요산',
    'nextDistance' : '1.6km',
    'preStop' : '망월사 / 도봉산(급행)',
    'preToward' : '인천',
    'preDistance' : '1.4km / 3.7km',
    'Company' : '한국철도공사',
    'Line' : '경원선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '망월사',
    'ENName' : 'Mangwolsa',
    'Num' : '112',
    'Transfer' : None,
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '회룡',
    'nextToward' : '소요산',
    'nextDistance' : '1.4km',
    'preStop' : '도봉산',
    'preToward' : '인천',
    'preDistance' : '1.2km',
    'Company' : '한국철도공사',
    'Line' : '경원선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '도봉산',
    'ENName' : 'Dobongsan',
    'Num' : '113',
    'Transfer' : '7호선',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '망월사 / 회룡(급행)',
    'nextToward' : '소요산',
    'nextDistance' : '1.2km / 3.7km',
    'preStop' : '도봉 / 창동(급행)',
    'preToward' : '인천',
    'preDistance' : '1.2km / 4.2km',
    'Company' : '한국철도공사',
    'Line' : '경원선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '도봉',
    'ENName' : 'Dobong',
    'Num' : '114',
    'Transfer' : None,
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '도봉산',
    'nextToward' : '소요산',
    'nextDistance' : '1.2km',
    'preStop' : '방학',
    'preToward' : '인천',
    'preDistance' : '1.3km',
    'Company' : '한국철도공사',
    'Line' : '경원선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '방학',
    'ENName' : 'Banghak',
    'Num' : '115',
    'Transfer' : None,
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '도봉',
    'nextToward' : '소요산',
    'nextDistance' : '1.3km',
    'preStop' : '창동',
    'preToward' : '인천',
    'preDistance' : '1.7km',
    'Company' : '한국철도공사',
    'Line' : '경원선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '창동',
    'ENName' : 'Chang-dong',
    'Num' : '116',
    'Transfer' : '4호선',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '방학',
    'nextToward' : '소요산',
    'nextDistance' : '1.7km',
    'preStop' : '녹천 / 광운대(급행)',
    'preToward' : '인천',
    'preDistance' : '1.0km / 3.5km',
    'Company' : '한국철도공사',
    'Line' : '경원선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '녹천',
    'ENName' : 'Nokcheon',
    'Num' : '117',
    'Transfer' : None,
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '창동',
    'nextToward' : '소요산',
    'nextDistance' : '1.0km',
    'preStop' : '월계',
    'preToward' : '인천',
    'preDistance' : '1.4km',
    'Company' : '한국철도공사',
    'Line' : '경원선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '월계(인덕대학)',
    'ENName' : 'Wolgye(Indeok Collage)',
    'Num' : '118',
    'Transfer' : None,
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '녹천',
    'nextToward' : '소요산',
    'nextDistance' : '1.4km',
    'preStop' : '광운대',
    'preToward' : '인천',
    'preDistance' : '1.1km',
    'Company' : '한국철도공사',
    'Line' : '경원선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '광운대',
    'ENName' : 'Kwangwoon Univ.',
    'Num' : '119',
    'Transfer' : '경춘선(시간표 확인 필요)',
    'Doors' : '왼쪽(상행) / 오른쪽(하행)',
    'Terminal' : 'Yes',
    'nextStop' : '월계',
    'nextToward' : '소요산',
    'nextDistance' : '1.1km',
    'preStop' : '석계',
    'preToward' : '인천 / 신창',
    'preDistance' : '1.1km',
    'Company' : '한국철도공사',
    'Line' : '경원선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '석계',
    'ENName' : 'Seokgye',
    'Num' : '120',
    'Transfer' : '6호선',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '광운대',
    'nextToward' : '소요산',
    'nextDistance' : '1.1km',
    'preStop' : '신이문',
    'preToward' : '인천 / 신창',
    'preDistance' : '1.4km',
    'Company' : '한국철도공사',
    'Line' : '경원선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '신이문',
    'ENName' : 'Sinimun',
    'Num' : '121',
    'Transfer' : None,
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '석계',
    'nextToward' : '소요산',
    'nextDistance' : '1.4km',
    'preStop' : '외대앞',
    'preToward' : '인천 / 신창',
    'preDistance' : '0.8km',
    'Company' : '한국철도공사',
    'Line' : '경원선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '외대앞',
    'ENName' : 'Hanguk Univ. of Foreign Studies',
    'Num' : '122',
    'Transfer' : None,
    'Doors' : '오른쪽(상행) / 왼쪽(하행)',
    'Terminal' : 'No',
    'nextStop' : '신이문',
    'nextToward' : '소요산',
    'nextDistance' : '0.8km',
    'preStop' : '회기',
    'preToward' : '인천 / 신창',
    'preDistance' : '0.8km',
    'Company' : '한국철도공사',
    'Line' : '경원선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '회기',
    'ENName' : 'Hoegi',
    'Num' : '123',
    'Transfer' : '경의중앙선,\n경춘선(시간표 확인 필요)',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '외대앞',
    'nextToward' : '소요산',
    'nextDistance' : '0.8km',
    'preStop' : '청량리',
    'preToward' : '인천 / 신창',
    'preDistance' : '1.4km',
    'Company' : '한국철도공사',
    'Line' : '경원선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '청량리(서울시립대입구)',
    'ENName' : 'Cheongnyangni(University of Seoul)',
    'Num' : '124',
    'Transfer' : '경의중앙선,\n수인분당선(시간표 확인 필요),\n경춘선(시간표 확인 필요)',
    'Doors' : '오른쪽',
    'Terminal' : 'Yes',
    'nextStop' : '회기',
    'nextToward' : '소요산',
    'nextDistance' : '1.4km',
    'preStop' : '제기동',
    'preToward' : '인천 / 신창',
    'preDistance' : '1.0km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 1호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '제기동(한국건강관리협회)',
    'ENName' : 'Jegi-dong(Korea Association of Health Promotion)',
    'Num' : '125',
    'Transfer' : None,
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '청량리',
    'nextToward' : '소요산',
    'nextDistance' : '1.0km',
    'preStop' : '신설동',
    'preToward' : '인천 / 신창',
    'preDistance' : '0.9km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 1호선',
    'watchStep' : 'Yes'
    },

    {
    'KRName' : '신설동',
    'ENName' : 'Sinseol-dong',
    'Num' : '126',
    'Transfer' : '2호선 성수지선,\n우이신설선',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '제기동',
    'nextToward' : '소요산',
    'nextDistance' : '0.9km',
    'preStop' : '동묘앞',
    'preToward' : '인천 / 신창',
    'preDistance' : '0.7km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 1호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '동묘앞',
    'ENName' : 'Dongmyo',
    'Num' : '127',
    'Transfer' : '6호선',
    'Doors' : '왼쪽',
    'Terminal' : 'Yes',
    'nextStop' : '신설동',
    'nextToward' : '소요산',
    'nextDistance' : '0.7km',
    'preStop' : '동대문',
    'preToward' : '인천 / 신창',
    'preDistance' : '0.6km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 1호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '동대문',
    'ENName' : 'Dongdaemun',
    'Num' : '128',
    'Transfer' : '4호선',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '동묘앞',
    'nextToward' : '소요산',
    'nextDistance' : '0.6km',
    'preStop' : '종로5가',
    'preToward' : '인천 / 신창',
    'preDistance' : '0.8km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 1호선',
    'watchStep' : 'Yes'
    },

    {
    'KRName' : '종로5가',
    'ENName' : 'Jongno 5(o)-ga',
    'Num' : '129',
    'Transfer' : None,
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '동대문',
    'nextToward' : '소요산',
    'nextDistance' : '0.8km',
    'preStop' : '종로3가',
    'preToward' : '인천 / 신창',
    'preDistance' : '0.9km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 1호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '종로3가',
    'ENName' : 'Jongno 3(sam)-ga',
    'Num' : '130',
    'Transfer' : '3호선,\n5호선',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '종로5가',
    'nextToward' : '소요산',
    'nextDistance' : '0.9km',
    'preStop' : '종각',
    'preToward' : '인천 / 신창',
    'preDistance' : '0.8km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 1호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '종각(SC제일은행)',
    'ENName' : 'Jonggak(Standard Chartered Bank Korea)',
    'Num' : '131',
    'Transfer' : None,
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '종로3가',
    'nextToward' : '소요산',
    'nextDistance' : '0.8km',
    'preStop' : '시청',
    'preToward' : '인천 / 신창',
    'preDistance' : '1.0km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 1호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '시청',
    'ENName' : 'City Hall',
    'Num' : '132',
    'Transfer' : '2호선',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '종각',
    'nextToward' : '소요산',
    'nextDistance' : '1.0km',
    'preStop' : '서울역',
    'preToward' : '인천 / 신창',
    'preDistance' : '1.1km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 1호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '서울역',
    'ENName' : 'Seoul Station',
    'Num' : '133',
    'Transfer' : '4호선,\n공항철도,\n경의중앙선(시간표 확인 필요)',
    'Doors' : '오른쪽',
    'Terminal' : 'lastTrain',
    'nextStop' : '시청',
    'nextToward' : '소요산',
    'nextDistance' : '1.1km',
    'preStop' : '남영',
    'preToward' : '인천 / 신창',
    'preDistance' : '1.7km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 1호선 / 경부선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '남영',
    'ENName' : 'Namyeong',
    'Num' : '134',
    'Transfer' : None,
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '서울역',
    'nextToward' : '소요산',
    'nextDistance' : '1.7km',
    'preStop' : '용산',
    'preToward' : '인천 / 신창',
    'preDistance' : '1.5km',
    'Company' : '한국철도공사',
    'Line' : '경부선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '용산',
    'ENName' : 'Yongsan',
    'Num' : '135',
    'Transfer' : '경의중앙선',
    'Doors' : '왼쪽(일반) / 양쪽(용산급행)',
    'Terminal' : 'Yes',
    'nextStop' : '남영',
    'nextToward' : '소요산',
    'nextDistance' : '1.5km',
    'preStop' : '노량진',
    'preToward' : '인천 / 신창',
    'preDistance' : '2.6km',
    'Company' : '한국철도공사',
    'Line' : '경부선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '노량진',
    'ENName' : 'Noryangjin',
    'Num' : '136',
    'Transfer' : '9호선',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '용산',
    'nextToward' : '소요산',
    'nextDistance' : '2.6km',
    'preStop' : '대방',
    'preToward' : '인천 / 신창',
    'preDistance' : '1.5km',
    'Company' : '한국철도공사',
    'Line' : '경부선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '대방',
    'ENName' : 'Daebang',
    'Num' : '137',
    'Transfer' : '신림선',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '노량진',
    'nextToward' : '소요산',
    'nextDistance' : '1.5km',
    'preStop' : '신길',
    'preToward' : '인천 / 신창',
    'preDistance' : '0.8km',
    'Company' : '한국철도공사',
    'Line' : '경부선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '신길',
    'ENName' : 'Singil',
    'Num' : '138',
    'Transfer' : '5호선',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '대방',
    'nextToward' : '소요산',
    'nextDistance' : '0.8km',
    'preStop' : '영등포',
    'preToward' : '인천 / 신창',
    'preDistance' : '1.0km',
    'Company' : '한국철도공사',
    'Line' : '경부선',
    'watchStep' : 'Yes'
    },

    {
    'KRName' : '영등포',
    'ENName' : 'Yeongdeungpo',
    'Num' : '139',
    'Transfer' : None,
    'Doors' : '왼쪽',
    'Terminal' : 'Yes',
    'nextStop' : '신길',
    'nextToward' : '소요산',
    'nextDistance' : '1.0km',
    'preStop' : '신도림',
    'preToward' : '인천 / 신창',
    'preDistance' : '1.5km',
    'Company' : '한국철도공사',
    'Line' : '경부선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '신도림',
    'ENName' : 'Sindorim',
    'Num' : '140',
    'Transfer' : '2호선,\n2호선 신정지선',
    'Doors' : '왼쪽(상행) / 오른쪽(하행)',
    'Terminal' : 'No',
    'nextStop' : '영등포',
    'nextToward' : '소요산',
    'nextDistance' : '1.5km',
    'preStop' : '구로',
    'preToward' : '인천 / 신창',
    'preDistance' : '1.1km',
    'Company' : '한국철도공사',
    'Line' : '경부선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '구로',
    'ENName' : 'Guro',
    'Num' : '141',
    'Transfer' : '인천행 <-> 신창행',
    'Doors' : '양쪽',
    'Terminal' : 'Yes',
    'nextStop' : '신도림',
    'nextToward' : '소요산',
    'nextDistance' : '1.1km',
    'preStop' : '구일 / 가산디지털단지',
    'preToward' : '인천 / 신창',
    'preDistance' : '1.4km / 2.4km',
    'Company' : '한국철도공사',
    'Line' : '경부선 / 경인선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '구일',
    'ENName' : 'Guil',
    'Num' : '142',
    'Transfer' : None,
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '구로',
    'nextToward' : '소요산',
    'nextDistance' : '1.4km',
    'preStop' : '개봉',
    'preToward' : '인천',
    'preDistance' : '1.0km',
    'Company' : '한국철도공사',
    'Line' : '경인선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '개봉',
    'ENName' : 'Gaebong',
    'Num' : '143',
    'Transfer' : None,
    'Doors' : '오른쪽(완행) / 왼쪽(급행)',
    'Terminal' : 'No',
    'nextStop' : '구일 / 구로(급행)',
    'nextToward' : '소요산',
    'nextDistance' : '1.0km / 2.4',
    'preStop' : '오류동 / 역곡(급행)',
    'preToward' : '인천',
    'preDistance' : '1.0km / 4.5km',
    'Company' : '한국철도공사',
    'Line' : '경인선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '오류동',
    'ENName' : 'Oryu-dong',
    'Num' : '144',
    'Transfer' : None,
    'Doors' : '오른쪽',
    'Terminal' : 'emergency',
    'nextStop' : '개봉',
    'nextToward' : '소요산',
    'nextDistance' : '1.0km',
    'preStop' : '온수',
    'preToward' : '인천',
    'preDistance' : '1.9km',
    'Company' : '한국철도공사',
    'Line' : '경인선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '온수(성공회대입구)',
    'ENName' : 'Onsu(Sungkonghoe Univ.)',
    'Num' : '145',
    'Transfer' : '7호선',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '오류동',
    'nextToward' : '소요산',
    'nextDistance' : '1.9km',
    'preStop' : '역곡',
    'preToward' : '인천',
    'preDistance' : '1.3km',
    'Company' : '한국철도공사',
    'Line' : '경인선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '역곡(가톨릭대)',
    'ENName' : 'Yeokgok(The Catholic Univ.)',
    'Num' : '146',
    'Transfer' : None,
    'Doors' : '오른쪽(완행) / 왼쪽(급행)',
    'Terminal' : 'No',
    'nextStop' : '온수 / 개봉(급행) / 구로(특급)',
    'nextToward' : '소요산',
    'nextDistance' : '1.3km / 4.5km / 6.9km',
    'preStop' : '소사 / 부천(급행)',
    'preToward' : '인천',
    'preDistance' : '1.5km / 2.6km',
    'Company' : '한국철도공사',
    'Line' : '경인선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '소사(서울신대)',
    'ENName' : 'Sosa(Seoul Theological Univ.)',
    'Num' : '147',
    'Transfer' : '서해선',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '역곡',
    'nextToward' : '소요산',
    'nextDistance' : '1.5km',
    'preStop' : '부천',
    'preToward' : '인천',
    'preDistance' : '1.1km',
    'Company' : '한국철도공사',
    'Line' : '경인선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '부천(부천대학교)',
    'ENName' : 'Bucheon(Bucheon Univ.)',
    'Num' : '148',
    'Transfer' : None,
    'Doors' : '오른쪽(완행) / 왼쪽(급행)',
    'Terminal' : 'No',
    'nextStop' : '소사',
    'nextToward' : '소요산',
    'nextDistance' : '1.1km',
    'preStop' : '중동 / 송내(급행)',
    'preToward' : '인천',
    'preDistance' : '1.7km / 2.7km',
    'Company' : '한국철도공사',
    'Line' : '경인선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '중동',
    'ENName' : 'Jung-dong',
    'Num' : '149',
    'Transfer' : None,
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '부천',
    'nextToward' : '소요산',
    'nextDistance' : '1.7km',
    'preStop' : '송내',
    'preToward' : '인천',
    'preDistance' : '1.0km',
    'Company' : '한국철도공사',
    'Line' : '경인선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '송내',
    'ENName' : 'Songnae',
    'Num' : '150',
    'Transfer' : None,
    'Doors' : '오른쪽(완행) / 왼쪽(급행)',
    'Terminal' : 'No',
    'nextStop' : '중동 / 부천(급행)',
    'nextToward' : '소요산',
    'nextDistance' : '1.0km / 2.7km',
    'preStop' : '부개 / 부평(급행)',
    'preToward' : '인천',
    'preDistance' : '1.2km / 2.7km',
    'Company' : '한국철도공사',
    'Line' : '경인선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '부개',
    'ENName' : 'Bugae',
    'Num' : '151',
    'Transfer' : None,
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '송내',
    'nextToward' : '소요산',
    'nextDistance' : '1.2km',
    'preStop' : '부평',
    'preToward' : '인천',
    'preDistance' : '1.5km',
    'Company' : '한국철도공사',
    'Line' : '경인선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '부평(가톨릭대 인천성모병원)',
    'ENName' : "Bupyeong(The Catholic Univ. Incheon St. Mary's Hospital)",
    'Num' : '152',
    'Transfer' : '인천1호선',
    'Doors' : '오른쪽(완행) / 왼쪽(급행)',
    'Terminal' : 'Yes',
    'nextStop' : '부개',
    'nextToward' : '소요산',
    'nextDistance' : '1.5km',
    'preStop' : '백운 / 동암(급행) / 주안(특급)',
    'preToward' : '인천',
    'preDistance' : '1.7km / 3.2km / 5.6km',
    'Company' : '한국철도공사',
    'Line' : '경인선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '백운',
    'ENName' : 'Baegun',
    'Num' : '153',
    'Transfer' : None,
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '부평',
    'nextToward' : '소요산',
    'nextDistance' : '1.7km',
    'preStop' : '동암',
    'preToward' : '인천',
    'preDistance' : '1.5km',
    'Company' : '한국철도공사',
    'Line' : '경인선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '동암',
    'ENName' : 'Dongam',
    'Num' : '154',
    'Transfer' : None,
    'Doors' : '오른쪽(완행) / 왼쪽(급행)',
    'Terminal' : 'No',
    'nextStop' : '백운 / 부평(급행)',
    'nextToward' : '소요산',
    'nextDistance' : '1.7km / 3.2km',
    'preStop' : '간석 / 주안(급행)',
    'preToward' : '인천',
    'preDistance' : '1.2km / 2.4km',
    'Company' : '한국철도공사',
    'Line' : '경인선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '간석',
    'ENName' : 'Ganseok',
    'Num' : '155',
    'Transfer' : None,
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '동암',
    'nextToward' : '소요산',
    'nextDistance' : '1.7km',
    'preStop' : '주안',
    'preToward' : '인천',
    'preDistance' : '1.2km',
    'Company' : '한국철도공사',
    'Line' : '경인선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '주안',
    'ENName' : 'Juan',
    'Num' : '156',
    'Transfer' : '인천2호선',
    'Doors' : '오른쪽(완행) / 왼쪽(급행)',
    'Terminal' : 'No',
    'nextStop' : '간석 / 동암(급행) / 부평(특급)',
    'nextToward' : '소요산',
    'nextDistance' : '1.2km / 2.4km / 5.6km',
    'preStop' : '도화 / 제물포(급행) / 동인천(특급)',
    'preToward' : '인천',
    'preDistance' : '1.0km / 2.0km / 4.6km',
    'Company' : '한국철도공사',
    'Line' : '경인선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '도화',
    'ENName' : 'Dohwa',
    'Num' : '157',
    'Transfer' : None,
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '주안',
    'nextToward' : '소요산',
    'nextDistance' : '1.2km',
    'preStop' : '제물포',
    'preToward' : '인천',
    'preDistance' : '1.0km',
    'Company' : '한국철도공사',
    'Line' : '경인선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '제물포(인천대학교 제물포캠퍼스)',
    'ENName' : 'Jemulpo(Incheon Univ. Jemulpo Campus)',
    'Num' : '158',
    'Transfer' : None,
    'Doors' : '오른쪽(완행) / 왼쪽(급행)',
    'Terminal' : 'No',
    'nextStop' : '도화',
    'nextToward' : '소요산',
    'nextDistance' : '1.0km',
    'preStop' : '도원 / 동인천(급행)',
    'preToward' : '인천',
    'preDistance' : '1.4km / 2.6km',
    'Company' : '한국철도공사',
    'Line' : '경인선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '도원',
    'ENName' : 'Dowon',
    'Num' : '159',
    'Transfer' : None,
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '제물포',
    'nextToward' : '소요산',
    'nextDistance' : '1.4km',
    'preStop' : '동인천',
    'preToward' : '인천',
    'preDistance' : '1.2km',
    'Company' : '한국철도공사',
    'Line' : '경인선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '동인천',
    'ENName' : 'Dongincheon',
    'Num' : '160',
    'Transfer' : None,
    'Doors' : '오른쪽(완행) / 왼쪽(급행)',
    'Terminal' : 'Yes',
    'nextStop' : '도원',
    'nextToward' : '소요산',
    'nextDistance' : '1.2km',
    'preStop' : '인천',
    'preToward' : '인천',
    'preDistance' : '1.9km',
    'Company' : '한국철도공사',
    'Line' : '경인선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '인천',
    'ENName' : 'Incheon',
    'Num' : '161',
    'Transfer' : '수인분당선',
    'Doors' : '양쪽',
    'Terminal' : 'Yes',
    'nextStop' : '동인천',
    'nextToward' : '소요산',
    'nextDistance' : '1.9km',
    'preStop' : None,
    'preToward' : '인천',
    'preDistance' : None,
    'Company' : '한국철도공사',
    'Line' : '경인선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '가산디지털단지',
    'ENName' : 'Gasan Digital Complex',
    'Num' : 'P142',
    'Transfer' : '7호선',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '구로',
    'nextToward' : '광운대',
    'nextDistance' : '2.4km',
    'preStop' : '독산 / 금천구청(통급) / 안양(급행)',
    'preToward' : '신창',
    'preDistance' : '2.0km / 3.2km / 9.8km',
    'Company' : '한국철도공사',
    'Line' : '경부선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '독산',
    'ENName' : 'Doksan',
    'Num' : 'P143',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '가산디지털단지',
    'nextToward' : '광운대',
    'nextDistance' : '1.9km',
    'preStop' : '금천구청',
    'preToward' : '신창',
    'preDistance' : '1.2km',
    'Company' : '한국철도공사',
    'Line' : '경부선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '금천구청',
    'ENName' : 'Geumcheon-gu Office',
    'Num' : 'P144',
    'Transfer' : '1호선 광명셔틀',
    'Doors' : '오른쪽(완행) / 왼쪽(급행)',
    'Terminal' : 'No',
    'nextStop' : '독산',
    'nextToward' : '광운대',
    'nextDistance' : '1.2km',
    'preStop' : '석수 / 안양(통급) / 광명(광명셔틀)',
    'preToward' : '신창 / 신창 / 광명',
    'preDistance' : '2.3km / 6.6km / 4.7km',
    'Company' : '한국철도공사',
    'Line' : '경부선 / 경부고속선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '광명',
    'ENName' : 'Gwangmyeong',
    'Num' : 'P144-1',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'Yes',
    'nextStop' : '금천구청',
    'nextToward' : '영등포',
    'nextDistance' : '4.7km',
    'preStop' : None,
    'preToward' : '광명',
    'preDistance' : None,
    'Company' : '한국철도공사',
    'Line' : '경부고속선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '석수',
    'ENName' : 'Seoksu',
    'Num' : 'P145',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '금천구청',
    'nextToward' : '광운대',
    'nextDistance' : '2.3km',
    'preStop' : '관악',
    'preToward' : '신창',
    'preDistance' : '1.9km',
    'Company' : '한국철도공사',
    'Line' : '경부선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '관악',
    'ENName' : 'Gwanak',
    'Num' : 'P146',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '석수',
    'nextToward' : '광운대',
    'nextDistance' : '1.9km',
    'preStop' : '안양',
    'preToward' : '신창',
    'preDistance' : '2.4km',
    'Company' : '한국철도공사',
    'Line' : '경부선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '안양',
    'ENName' : 'Anyang',
    'Num' : 'P147',
    'Transfer' : 'No',
    'Doors' : '오른쪽(완행 / 일반 급행) / 왼쪽(서울역 급행)',
    'Terminal' : 'No',
    'nextStop' : '관악 / 금천구청(통급) / 가산디지털단지(급행 A)',
    'nextToward' : '광운대',
    'nextDistance' : '2.4km / 6.6km / 9.8km',
    'preStop' : '명학 / 금정(급행 A) / 군포(천안 급행)',
    'preToward' : '신창 / 신창 / 천안',
    'preDistance' : '2.2km / 3.6km / 5.8km',
    'Company' : '한국철도공사',
    'Line' : '경부선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '명학',
    'ENName' : 'Myeonghak',
    'Num' : 'P148',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '안양',
    'nextToward' : '광운대',
    'nextDistance' : '2.2km',
    'preStop' : '금정',
    'preToward' : '신창',
    'preDistance' : '1.4km',
    'Company' : '한국철도공사',
    'Line' : '경부선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '금정',
    'ENName' : 'Geumjeong',
    'Num' : 'P149',
    'Transfer' : '4호선',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '명학 / 안양(급행 A)',
    'nextToward' : '광운대',
    'nextDistance' : '1.4km',
    'preStop' : '군포 / 의왕(통급) / 성균관대(급행 A)',
    'preToward' : '신창',
    'preDistance' : '2.2km / 6.4km / 9.3km',
    'Company' : '한국철도공사',
    'Line' : '경부선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '군포',
    'ENName' : 'Gunpo',
    'Num' : 'P150',
    'Transfer' : 'No',
    'Doors' : '오른쪽(완행) / 왼쪽(급행)',
    'Terminal' : 'No',
    'nextStop' : '금정 / 안양(급행)',
    'nextToward' : '광운대',
    'nextDistance' : '2.2km / 5.8km',
    'preStop' : '당정 / 의왕(급행)',
    'preToward' : '신창',
    'preDistance' : '1.6km / 4.2km',
    'Company' : '한국철도공사',
    'Line' : '경부선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '당정',
    'ENName' : 'Dangjeong',
    'Num' : 'P151',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '군포',
    'nextToward' : '광운대',
    'nextDistance' : '1.6km',
    'preStop' : '의왕',
    'preToward' : '신창',
    'preDistance' : '2.6km',
    'Company' : '한국철도공사',
    'Line' : '경부선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '의왕',
    'ENName' : 'Uiwang',
    'Num' : 'P152',
    'Transfer' : 'No',
    'Doors' : '오른쪽(완행 / 급행 A) / 왼쪽(급행)',
    'Terminal' : 'No',
    'nextStop' : '당정 / 금정(통급) / 군포(급행 A)',
    'nextToward' : '광운대',
    'nextDistance' : '2.6km / 6.4km / 4.2km',
    'preStop' : '당정',
    'preToward' : '신창',
    'preDistance' : '2.9km',
    'Company' : '한국철도공사',
    'Line' : '경부선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '성균관대',
    'ENName' : 'Sungkyunkwan Univ.',
    'Num' : 'P153',
    'Transfer' : 'No',
    'Doors' : '오른쪽(완행 / 급행 A) / 왼쪽(급행)',
    'Terminal' : 'No',
    'nextStop' : '의왕(완행 / 통급 / 급행) / 금정(급행 A)',
    'nextToward' : '광운대',
    'nextDistance' : '2.9km / 9.3km',
    'preStop' : '화서(완행) / 수원(급행)',
    'preToward' : '신창',
    'preDistance' : '2.6km / 4.7km',
    'Company' : '한국철도공사',
    'Line' : '경부선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '화서',
    'ENName' : 'Hwaseo',
    'Num' : 'P154',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '성균관대',
    'nextToward' : '광운대',
    'nextDistance' : '2.6km',
    'preStop' : '수원',
    'preToward' : '신창',
    'preDistance' : '2.1km',
    'Company' : '한국철도공사',
    'Line' : '경부선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '수원',
    'ENName' : 'Suwon',
    'Num' : 'P155',
    'Transfer' : '수인분당선',
    'Doors' : '왼쪽(상행) / 오른쪽(하행)',
    'Terminal' : 'No',
    'nextStop' : '화서(완행) / 성균관대(급행)',
    'nextToward' : '광운대',
    'nextDistance' : '2.1km / 4.7km',
    'preStop' : '세류(완행) / 병점(급행)',
    'preToward' : '신창',
    'preDistance' : '2.9km / 7.2km',
    'Company' : '한국철도공사',
    'Line' : '경부선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '세류',
    'ENName' : 'Seryu',
    'Num' : 'P156',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '수원',
    'nextToward' : '광운대',
    'nextDistance' : '2.9km',
    'preStop' : '병점',
    'preToward' : '신창',
    'preDistance' : '4.3km',
    'Company' : '한국철도공사',
    'Line' : '경부선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '병점(한신대)',
    'ENName' : 'Byeongjeom(Hanshin Univ.)',
    'Num' : 'P157',
    'Transfer' : '서동탄행 <-> 천안행',
    'Doors' : '왼쪽(천안행 / 천안발) / 오른쪽(서동탄행 / 서동탄발)',
    'Terminal' : 'Yes',
    'nextStop' : '세류 / 수원(급행)',
    'nextToward' : '광운대',
    'nextDistance' : '4.3 / 7.2km',
    'preStop' : '세마 / 서동탄',
    'preToward' : '신창 / 서동탄',
    'preDistance' : '2.4km / 2.2km',
    'Company' : '한국철도공사',
    'Line' : '경부선 / 병점기지선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '서동탄',
    'ENName' : 'Seodongtan',
    'Num' : 'P157-1',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'Yes',
    'nextStop' : '병점',
    'nextToward' : '광운대',
    'nextDistance' : '2.2km',
    'preStop' : None,
    'preToward' : '서동탄',
    'preDistance' : None,
    'Company' : '한국철도공사',
    'Line' : '병점기지선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '세마',
    'ENName' : 'Sema',
    'Num' : 'P158',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '병점',
    'nextToward' : '광운대',
    'nextDistance' : '2.4km',
    'preStop' : '오산대',
    'preToward' : '신창',
    'preDistance' : '2.7km',
    'Company' : '한국철도공사',
    'Line' : '경부선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '오산대',
    'ENName' : 'Osan Univ.',
    'Num' : 'P159',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '세마',
    'nextToward' : '광운대',
    'nextDistance' : '2.7km',
    'preStop' : '오산',
    'preToward' : '신창',
    'preDistance' : '2.7km',
    'Company' : '한국철도공사',
    'Line' : '경부선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '오산',
    'ENName' : 'Osan',
    'Num' : 'P160',
    'Transfer' : 'No',
    'Doors' : '왼쪽 / 오른쪽(대피선)',
    'Terminal' : 'No',
    'nextStop' : '오산대 / 병점(급행)',
    'nextToward' : '광운대',
    'nextDistance' : '2.7km / 7.8km',
    'preStop' : '진위 / 서정리(급행)',
    'preToward' : '신창',
    'preDistance' : '4.0km / 10.0km',
    'Company' : '한국철도공사',
    'Line' : '경부선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '진위',
    'ENName' : 'Jinwi',
    'Num' : 'P161',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '오산',
    'nextToward' : '광운대',
    'nextDistance' : '4.0km',
    'preStop' : '송탄',
    'preToward' : '신창',
    'preDistance' : '3.8km',
    'Company' : '한국철도공사',
    'Line' : '경부선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '송탄',
    'ENName' : 'Songtan',
    'Num' : 'P162',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '진위',
    'nextToward' : '광운대',
    'nextDistance' : '3.8km',
    'preStop' : '서정리',
    'preToward' : '신창',
    'preDistance' : '2.2km',
    'Company' : '한국철도공사',
    'Line' : '경부선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '서정리(국제대학)',
    'ENName' : 'Seojeong-ri(Kookje Univ.)',
    'Num' : 'P163',
    'Transfer' : 'No',
    'Doors' : '양쪽',
    'Terminal' : 'No',
    'nextStop' : '송탄(완행) / 오산(급행)',
    'nextToward' : '광운대',
    'nextDistance' : '2.2km / 10.0km',
    'preStop' : '평택지제(완행) / 평택(급행)',
    'preToward' : '신창',
    'preDistance' : '4.8km / 8.5km',
    'Company' : '한국철도공사',
    'Line' : '경부선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '평택지제(한경국립대)',
    'ENName' : 'PyeongtaekJije(Hankyeong National Univ.)',
    'Num' : 'P164',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '서정리',
    'nextToward' : '광운대',
    'nextDistance' : '4.8km',
    'preStop' : '평택',
    'preToward' : '신창',
    'preDistance' : '3.7km',
    'Company' : '한국철도공사',
    'Line' : '경부선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '평택',
    'ENName' : 'Pyeongtaek',
    'Num' : 'P165',
    'Transfer' : 'No',
    'Doors' : '양쪽',
    'Terminal' : 'No',
    'nextStop' : '평택지제(완행) / 서정리(급행)',
    'nextToward' : '광운대',
    'nextDistance' : '3.7km / 8.5km',
    'preStop' : '성환',
    'preToward' : '신창',
    'preDistance' : '9.4km',
    'Company' : '한국철도공사',
    'Line' : '경부선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '성환',
    'ENName' : 'Seonghwan',
    'Num' : 'P166',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '평택',
    'nextToward' : '광운대',
    'nextDistance' : '9.4km',
    'preStop' : '직산(완행) / 두정(급행)',
    'preToward' : '신창',
    'preDistance' : '5.4km / 9.2km',
    'Company' : '한국철도공사',
    'Line' : '경부선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '직산',
    'ENName' : 'Jiksan',
    'Num' : 'P167',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '성환',
    'nextToward' : '광운대',
    'nextDistance' : '5.4km',
    'preStop' : '두정',
    'preToward' : '신창',
    'preDistance' : '3.8km',
    'Company' : '한국철도공사',
    'Line' : '경부선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '두정',
    'ENName' : 'Dujeong',
    'Num' : 'P168',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '직산(완행) / 성환(급행)',
    'nextToward' : '광운대',
    'nextDistance' : '3.8km / 9.2km',
    'preStop' : '천안',
    'preToward' : '신창',
    'preDistance' : '3.1km',
    'Company' : '한국철도공사',
    'Line' : '경부선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '천안',
    'ENName' : 'Cheonan',
    'Num' : 'P169',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'Yes',
    'nextStop' : '두정',
    'nextToward' : '광운대',
    'nextDistance' : '3.1km',
    'preStop' : '봉명',
    'preToward' : '신창',
    'preDistance' : '1.3km',
    'Company' : '한국철도공사',
    'Line' : '장항선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '봉명',
    'ENName' : 'Bongmyeong',
    'Num' : 'P170',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '천안',
    'nextToward' : '광운대',
    'nextDistance' : '1.3km',
    'preStop' : '쌍용',
    'preToward' : '신창',
    'preDistance' : '1.6km',
    'Company' : '한국철도공사',
    'Line' : '장항선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '쌍용(나사렛대)',
    'ENName' : 'Ssangyong(Korea Nazarene Univ.)',
    'Num' : 'P171',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '봉명',
    'nextToward' : '광운대',
    'nextDistance' : '1.6km',
    'preStop' : '아산',
    'preToward' : '신창',
    'preDistance' : '1.6km',
    'Company' : '한국철도공사',
    'Line' : '장항선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '아산(선문대)',
    'ENName' : 'Asan(Sunmoon Univ.)',
    'Num' : 'P172',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '쌍용',
    'nextToward' : '광운대',
    'nextDistance' : '1.6km',
    'preStop' : '탕정',
    'preToward' : '신창',
    'preDistance' : '1.8km',
    'Company' : '한국철도공사',
    'Line' : '장항선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '탕정',
    'ENName' : 'Tangjeong',
    'Num' : 'P173',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '아산',
    'nextToward' : '광운대',
    'nextDistance' : '1.8km',
    'preStop' : '배방',
    'preToward' : '신창',
    'preDistance' : '3.1km',
    'Company' : '한국철도공사',
    'Line' : '장항선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '배방',
    'ENName' : 'Baebang',
    'Num' : 'P174',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '탕정',
    'nextToward' : '광운대',
    'nextDistance' : '3.1km',
    'preStop' : '온양온천',
    'preToward' : '신창',
    'preDistance' : '4.9km',
    'Company' : '한국철도공사',
    'Line' : '장항선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '풍기',
    'ENName' : 'Punggi',
    'Num' : 'P175',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '배방',
    'nextToward' : '광운대',
    'nextDistance' : '2.6km',
    'preStop' : '온양온천',
    'preToward' : '신창',
    'preDistance' : '2.3km',
    'Company' : '한국철도공사',
    'Line' : '장항선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '온양온천',
    'ENName' : 'Onyang Oncheon',
    'Num' : 'P176',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '배방',
    'nextToward' : '광운대',
    'nextDistance' : '4.9km',
    'preStop' : '신창',
    'preToward' : '신창',
    'preDistance' : '5.1km',
    'Company' : '한국철도공사',
    'Line' : '장항선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '신창(순천향대)',
    'ENName' : 'Sinchang(Sooncheonghyang Univ.)',
    'Num' : 'P177',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'Yes',
    'nextStop' : '온양온천',
    'nextToward' : '광운대',
    'nextDistance' : '5.1km',
    'preStop' : None,
    'preToward' : '신창',
    'preDistance' : None,
    'Company' : '한국철도공사',
    'Line' : '장항선',
    'watchStep' : 'No'
    },

    ]
