class stn():
    stns = [{}, {
    'KRName' : '시청',
    'ENName' : 'City Hall',
    'Num' : '201',
    'Transfer' : '1호선',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '충정로',
    'nextToward' : '외선',
    'nextDistance' : '1.1km',
    'preStop' : '을지로입구',
    'preToward' : '내선',
    'preDistance' : '0.7km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 2호선',
    'watchStep' : 'Yes'
    },

    {
    'KRName' : '을지로입구(하나은행)',
    'ENName' : 'Euljiro 1(il)-ga(Hana Bank)',
    'Num' : '202',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'lastTrain',
    'nextStop' : '시청',
    'nextToward' : '외선',
    'nextDistance' : '0.7km',
    'preStop' : '을지로3가',
    'preToward' : '내선',
    'preDistance' : '0.8km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 2호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '을지로3가(신한카드)',
    'ENName' : 'Euljiro 3(sam)-ga(Shinhan Card)',
    'Num' : '203',
    'Transfer' : '3호선',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '을지로입구',
    'nextToward' : '외선',
    'nextDistance' : '0.8km',
    'preStop' : '을지로4가',
    'preToward' : '내선',
    'preDistance' : '0.6km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 2호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '을지로4가(BC카드)',
    'ENName' : 'Euljiro 4(sa)-ga(BC Card)',
    'Num' : '204',
    'Transfer' : '5호선',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '을지로3가',
    'nextToward' : '외선',
    'nextDistance' : '0.6km',
    'preStop' : '동대문역사문화공원',
    'preToward' : '내선',
    'preDistance' : '1.0km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 2호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '동대문역사문화공원(DDP)',
    'ENName' : 'Dongdaemun History & Culture Park(DDP)',
    'Num' : '205',
    'Transfer' : '4호선,\n5호선',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '을지로4가',
    'nextToward' : '외선',
    'nextDistance' : '1.0km',
    'preStop' : '신당',
    'preToward' : '내선',
    'preDistance' : '0.9km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 2호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '신당',
    'ENName' : 'Sindang',
    'Num' : '206',
    'Transfer' : '6호선',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '동대문역사문화공원',
    'nextToward' : '외선',
    'nextDistance' : '0.9km',
    'preStop' : '상왕십리',
    'preToward' : '내선',
    'preDistance' : '0.9km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 2호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '상왕십리',
    'ENName' : 'Sangwangsimni',
    'Num' : '207',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '신당',
    'nextToward' : '외선',
    'nextDistance' : '0.9km',
    'preStop' : '왕십리',
    'preToward' : '내선',
    'preDistance' : '0.8km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 2호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '왕십리(성동구청)',
    'ENName' : 'Wangsimni(Seongdong-gu Office)',
    'Num' : '208',
    'Transfer' : '5호선,\n경의중앙선,\n수인분당',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '상왕십리',
    'nextToward' : '외선',
    'nextDistance' : '0.8km',
    'preStop' : '한양대',
    'preToward' : '내선',
    'preDistance' : '1.0km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 2호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '한양대',
    'ENName' : 'Hanyang Univ.',
    'Num' : '209',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '왕십리',
    'nextToward' : '외선',
    'nextDistance' : '1.0km',
    'preStop' : '뚝섬',
    'preToward' : '내선',
    'preDistance' : '1.1km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 2호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '뚝섬',
    'ENName' : 'Ttukseom',
    'Num' : '210',
    'Transfer' : 'None',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '한양대',
    'nextToward' : '외선',
    'nextDistance' : '1.1km',
    'preStop' : '성수',
    'preToward' : '내선',
    'preDistance' : '0.8km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 2호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '성수',
    'ENName' : 'Seongsu',
    'Num' : '211',
    'Transfer' : '2호선 성수지선',
    'Doors' : '오른쪽',
    'Terminal' : 'Yes',
    'nextStop' : '뚝섬',
    'nextToward' : '외선',
    'nextDistance' : '0.8km',
    'preStop' : '건대입구 / 용답(성수지선)',
    'preToward' : '내선 / 신설동',
    'preDistance' : '1.2km / 2.3km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 2호선 / 성수지선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '건대입구',
    'ENName' : 'Konkuk Univ.',
    'Num' : '212',
    'Transfer' : '7호선',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '성수',
    'nextToward' : '외선',
    'nextDistance' : '1.2km',
    'preStop' : '구의',
    'preToward' : '내선',
    'preDistance' : '1.6km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 2호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '구의(광진구청)',
    'ENName' : 'Guui(Gwangjin-gu Office)',
    'Num' : '213',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '건대입구',
    'nextToward' : '외선',
    'nextDistance' : '1.6km',
    'preStop' : '강변',
    'preToward' : '내선',
    'preDistance' : '0.9km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 2호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '강변(동서울터미널)',
    'ENName' : 'Gangbyeon(Dongseoul Bus Terminal)',
    'Num' : '214',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '구의',
    'nextToward' : '외선',
    'nextDistance' : '0.9km',
    'preStop' : '잠실나루',
    'preToward' : '내선',
    'preDistance' : '1.8km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 2호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '잠실나루',
    'ENName' : 'Jamsilnaru',
    'Num' : '215',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '강변',
    'nextToward' : '외선',
    'nextDistance' : '1.8km',
    'preStop' : '잠실',
    'preToward' : '내선',
    'preDistance' : '1.0km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 2호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '잠실(송파구청)',
    'ENName' : 'Jamsil(Songpa-gu Office)',
    'Num' : '216',
    'Transfer' : '8호선',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '잠실나루',
    'nextToward' : '외선',
    'nextDistance' : '1.0km',
    'preStop' : '잠실새내',
    'preToward' : '내선',
    'preDistance' : '1.2km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 2호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '잠실새내',
    'ENName' : 'Jamsilsaenae',
    'Num' : '217',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '잠실',
    'nextToward' : '외선',
    'nextDistance' : '1.2km',
    'preStop' : '종합운동장',
    'preToward' : '내선',
    'preDistance' : '1.2km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 2호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '종합운동장',
    'ENName' : 'Sports Complex',
    'Num' : '218',
    'Transfer' : '9호선',
    'Doors' : '오른쪽',
    'Terminal' : 'emergency',
    'nextStop' : '잠실새내',
    'nextToward' : '외선',
    'nextDistance' : '1.2km',
    'preStop' : '삼성',
    'preToward' : '내선',
    'preDistance' : '1.0km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 2호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '삼성(무역센터)',
    'ENName' : 'Samseong(World Trade Center Seoul)',
    'Num' : '219',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'lastTrain',
    'nextStop' : '종합운동장',
    'nextToward' : '외선',
    'nextDistance' : '1.0km',
    'preStop' : '선릉',
    'preToward' : '내선',
    'preDistance' : '1.3km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 2호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '선릉(애큐온저축은행)',
    'ENName' : 'Seolleung(Acuon Savings Bank)',
    'Num' : '220',
    'Transfer' : '수인분당선',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '삼성',
    'nextToward' : '외선',
    'nextDistance' : '1.3km',
    'preStop' : '역삼',
    'preToward' : '내선',
    'preDistance' : '1.2km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 2호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '역삼(센터필드)',
    'ENName' : 'Yeoksam(CENTERFIELD)',
    'Num' : '221',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '선릉',
    'nextToward' : '외선',
    'nextDistance' : '1.2km',
    'preStop' : '강남',
    'preToward' : '내선',
    'preDistance' : '0.8km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 2호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '강남',
    'ENName' : 'Gangnam',
    'Num' : '222',
    'Transfer' : '신분당선',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '역삼',
    'nextToward' : '외선',
    'nextDistance' : '0.8km',
    'preStop' : '교대',
    'preToward' : '내선',
    'preDistance' : '1.2km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 2호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '교대(법원, 검찰청)',
    'ENName' : "Seoul Nat'l Univ. of Education(Court & Prosecutor's Office)",
    'Num' : '223',
    'Transfer' : '3호선',
    'Doors' : '오른쪽',
    'Terminal' : 'emergency',
    'nextStop' : '강남',
    'nextToward' : '외선',
    'nextDistance' : '1.2km',
    'preStop' : '서초',
    'preToward' : '내선',
    'preDistance' : '0.7km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 2호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '서초',
    'ENName' : 'Seocho',
    'Num' : '224',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '교대',
    'nextToward' : '외선',
    'nextDistance' : '0.7km',
    'preStop' : '방배',
    'preToward' : '내선',
    'preDistance' : '1.7km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 2호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '방배(백석예술대)',
    'ENName' : 'Bangbae(Baekseok Arts Univ.)',
    'Num' : '225',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '서초',
    'nextToward' : '외선',
    'nextDistance' : '1.7km',
    'preStop' : '사당',
    'preToward' : '내선',
    'preDistance' : '1.6km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 2호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '사당(대항병원)',
    'ENName' : 'Sadang(Daehang Hospital)',
    'Num' : '226',
    'Transfer' : '4호선',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '방배',
    'nextToward' : '외선',
    'nextDistance' : '1.6km',
    'preStop' : '낙성대',
    'preToward' : '내선',
    'preDistance' : '1.7km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 2호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '낙성대(강감찬)',
    'ENName' : 'Nakseongdae(Ganggamchan)',
    'Num' : '227',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '사당',
    'nextToward' : '외선',
    'nextDistance' : '1.7km',
    'preStop' : '서울대입구',
    'preToward' : '내선',
    'preDistance' : '1.0km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 2호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '서울대입구(관악구청)',
    'ENName' : "Seoul Nat'l Univ.(Gwanak-gu Office)",
    'Num' : '228',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'lastTrain',
    'nextStop' : '낙성대',
    'nextToward' : '외선',
    'nextDistance' : '1.0km',
    'preStop' : '봉천',
    'preToward' : '내선',
    'preDistance' : '1.0km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 2호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '봉천',
    'ENName' : 'Bongcheon',
    'Num' : '229',
    'Transfer' : 'No',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '서울대입구',
    'nextToward' : '외선',
    'nextDistance' : '1.0km',
    'preStop' : '신림',
    'preToward' : '내선',
    'preDistance' : '1.1km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 2호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '신림',
    'ENName' : 'Sillim',
    'Num' : '230',
    'Transfer' : '신림선',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '봉천',
    'nextToward' : '외선',
    'nextDistance' : '1.1km',
    'preStop' : '신대방',
    'preToward' : '내선',
    'preDistance' : '1.8km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 2호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '신대방',
    'ENName' : 'Sindaebang',
    'Num' : '231',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '신림',
    'nextToward' : '외선',
    'nextDistance' : '1.8km',
    'preStop' : '구로디지털단지',
    'preToward' : '내선',
    'preDistance' : '1.1km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 2호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '구로디지털단지(원광디지털대)',
    'ENName' : 'Guro Digital Complex(Wonkwang Digital Univ.)',
    'Num' : '232',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '신대방',
    'nextToward' : '외선',
    'nextDistance' : '1.1km',
    'preStop' : '대림',
    'preToward' : '내선',
    'preDistance' : '1.1km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 2호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '대림(구로구청)',
    'ENName' : 'Daerim(Guro-gu Office)',
    'Num' : '233',
    'Transfer' : '7호선',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '구로디지털단지',
    'nextToward' : '외선',
    'nextDistance' : '1.1km',
    'preStop' : '신도림',
    'preToward' : '내선',
    'preDistance' : '1.8km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 2호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '신도림',
    'ENName' : 'Sindorim',
    'Num' : '234',
    'Transfer' : '1호선,\n2호선 신정지선',
    'Doors' : '왼쪽 / 오른쪽(본선 신도림 종착 열차)',
    'Terminal' : 'Yes',
    'nextStop' : '대림',
    'nextToward' : '외선',
    'nextDistance' : '1.8km',
    'preStop' : '문래 / 도림천(신정지선)',
    'preToward' : '내선 / 까치산',
    'preDistance' : '1.2km / 1.0km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 2호선 / 신정지선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '문래(김안과병원)',
    'ENName' : "Mullae(Kim's Eye Hospital)",
    'Num' : '235',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '신도림',
    'nextToward' : '외선',
    'nextDistance' : '1.2km',
    'preStop' : '영등포구청',
    'preToward' : '내선',
    'preDistance' : '0.9km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 2호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '영등포구청',
    'ENName' : 'Yeongdeungpo-gu Office',
    'Num' : '236',
    'Transfer' : '5호선',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '문래',
    'nextToward' : '외선',
    'nextDistance' : '0.9km',
    'preStop' : '당산',
    'preToward' : '내선',
    'preDistance' : '1.2km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 2호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '당산',
    'ENName' : 'Dangsan',
    'Num' : '237',
    'Transfer' : '9호선',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '영등포구청',
    'nextToward' : '외선',
    'nextDistance' : '1.2km',
    'preStop' : '합정',
    'preToward' : '내선',
    'preDistance' : '2.0km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 2호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '합정(홀트아동복지회)',
    'ENName' : "Hapjeong(Holt Children's Services, Inc.)",
    'Num' : '238',
    'Transfer' : '6호선',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '당산',
    'nextToward' : '외선',
    'nextDistance' : '2.0km',
    'preStop' : '홍대입구',
    'preToward' : '내선',
    'preDistance' : '1.1km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 2호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '홍대입구',
    'ENName' : 'Hongik Univ.',
    'Num' : '239',
    'Transfer' : '공항철도,\n경의중앙선',
    'Doors' : '오른쪽',
    'Terminal' : 'lastTrain',
    'nextStop' : '합정',
    'nextToward' : '외선',
    'nextDistance' : '1.1km',
    'preStop' : '신촌',
    'preToward' : '내선',
    'preDistance' : '1.3km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 2호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '신촌',
    'ENName' : 'Sinchon',
    'Num' : '240',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '홍대입구',
    'nextToward' : '외선',
    'nextDistance' : '1.3km',
    'preStop' : '이대',
    'preToward' : '내선',
    'preDistance' : '0.8km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 2호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '이대',
    'ENName' : "Ihwa Women's Univ.",
    'Num' : '241',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '신촌',
    'nextToward' : '외선',
    'nextDistance' : '0.8km',
    'preStop' : '아현',
    'preToward' : '내선',
    'preDistance' : '0.9km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 2호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '아현(추계예술대)',
    'ENName' : 'Ahyeon(Chugye Univ. for the Arts)',
    'Num' : '242',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '이대',
    'nextToward' : '외선',
    'nextDistance' : '0.9km',
    'preStop' : '충정로',
    'preToward' : '내선',
    'preDistance' : '0.8km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 2호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '충정로(경기대입구)',
    'ENName' : 'Chungjeongno(Kyeonggi Univ.)',
    'Num' : '243',
    'Transfer' : '5호선',
    'Doors' : '왼쪽',
    'Terminal' : 'No',
    'nextStop' : '아현',
    'nextToward' : '외선',
    'nextDistance' : '0.8km',
    'preStop' : '시청',
    'preToward' : '내선',
    'preDistance' : '1.1km',
    'Company' : '서울교통공사',
    'Line' : '서울 지하철 2호선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '용답',
    'ENName' : 'Yongdap',
    'Num' : '211-1',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '성수',
    'nextToward' : '성수',
    'nextDistance' : '2.3km',
    'preStop' : '신답',
    'preToward' : '신설동',
    'preDistance' : '1.0km',
    'Company' : '서울교통공사',
    'Line' : '성수지선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '신답',
    'ENName' : 'Sindap',
    'Num' : '211-2',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '용답',
    'nextToward' : '성수',
    'nextDistance' : '1.0km',
    'preStop' : '용두',
    'preToward' : '신설동',
    'preDistance' : '0.9km',
    'Company' : '서울교통공사',
    'Line' : '성수지선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '용두(동대문구청)',
    'ENName' : 'Yongdu(Dongdaemun-gu Office)',
    'Num' : '211-3',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '신답',
    'nextToward' : '성수',
    'nextDistance' : '0.9km',
    'preStop' : '신설동',
    'preToward' : '신설동',
    'preDistance' : '1.2km',
    'Company' : '서울교통공사',
    'Line' : '성수지선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '신설동',
    'ENName' : 'Sinseol-dong',
    'Num' : '211-4',
    'Transfer' : '1호선,\n우이신설선',
    'Doors' : '오른쪽',
    'Terminal' : 'Yes',
    'nextStop' : '용두',
    'nextToward' : '성수',
    'nextDistance' : '1.2km',
    'preStop' : None,
    'preToward' : '신설동',
    'preDistance' : None,
    'Company' : '서울교통공사',
    'Line' : '성수지선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '도림천',
    'ENName' : 'Dorimcheon',
    'Num' : '234-1',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'emergency',
    'nextStop' : '신도림',
    'nextToward' : '신도림',
    'nextDistance' : '1.0km',
    'preStop' : '양천구청',
    'preToward' : '까치산',
    'preDistance' : '1.7km',
    'Company' : '서울교통공사',
    'Line' : '신정지선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '양천구청',
    'ENName' : 'Yangcheon-gu Office',
    'Num' : '234-2',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '도림천',
    'nextToward' : '신도림',
    'nextDistance' : '1.7km',
    'preStop' : '신정네거리',
    'preToward' : '까치산',
    'preDistance' : '1.9km',
    'Company' : '서울교통공사',
    'Line' : '신정지선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '신정네거리',
    'ENName' : 'Sinjeongnegeori',
    'Num' : '234-3',
    'Transfer' : 'No',
    'Doors' : '오른쪽',
    'Terminal' : 'No',
    'nextStop' : '양천구청',
    'nextToward' : '신도림',
    'nextDistance' : '1.9km',
    'preStop' : '까치산',
    'preToward' : '까치산',
    'preDistance' : '1.4km',
    'Company' : '서울교통공사',
    'Line' : '신정지선',
    'watchStep' : 'No'
    },

    {
    'KRName' : '까치산',
    'ENName' : 'Kkachisan',
    'Num' : '234-4',
    'Transfer' : '5호선',
    'Doors' : '오른쪽',
    'Terminal' : 'Yes',
    'nextStop' : '신정네거리',
    'nextToward' : '신도림',
    'nextDistance' : '1.4km',
    'preStop' : None,
    'preToward' : '까치산',
    'preDistance' : None,
    'Company' : '서울교통공사',
    'Line' : '신정지선',
    'watchStep' : 'No'
    },
    ]
